# Generated by Django 3.1 on 2020-08-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20200831_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
