# Generated by Django 3.1 on 2020-08-31 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_sessions', '0002_session_patient'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedures.procedure'),
        ),
    ]
