# Generated by Django 3.1 on 2020-08-31 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0002_historicalmachine_history_user'),
        ('rooms', '0001_initial'),
        ('patient_sessions', '0003_session_procedure'),
        ('procedures', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='patient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='procedure',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='procedures.procedure'),
        ),
        migrations.AddField(
            model_name='historicalappointmentsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalappointmentsession',
            name='machine',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='historicalappointmentsession',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='historicalappointmentsession',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patient_sessions.session'),
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machines.machine'),
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patient_sessions.session'),
        ),
    ]
